# Versão estável do Python
FROM python:3.12-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia e instala as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do seu código (app.py, modelos, dados)
COPY . .

# Define o comando de inicialização Gunicorn na porta 8080
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]